Description of Sc
Sc
PURPOSE
constant term
SYNOPSIS
function sc = Sc(w1, w2, t)
DESCRIPTION
constant term
CROSS-REFERENCE INFORMATION
This function calls:
S original source term
dSdt derivative and the Sp term
This function is called by:
Finite_Volume_Method
SOURCE CODE
%constant term
function sc = Sc(w1, w2, t)
    sc = S(w1, w2, t) - (dSdt(w1, w2, t)) * t;
end