Description of adomain_decomposed
adomain_decomposed
PURPOSE
SYNOPSIS
function t = adomain_decomposed(theta_0,w1,w2,x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
P1
P2
P3
P4
This function is called by:
analytical_solution
SOURCE CODE
function t = adomain_decomposed(theta_0,w1,w2,x)
    t = theta_0 + ...
        P1(w1,w2,theta_0) * x.^2 + ...
        P2(w1,w2,theta_0) * x.^4 + ...
        P3(w1,w2,theta_0) * x.^6 + ...
        P4(w1,w2,theta_0) * x.^8;
end