Description of compute_w
compute_w
PURPOSE
SYNOPSIS
function s = compute_w(Ra,Da,Nu,psi,xi,k_r)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
analytical_solution
Finite_Volume_Method
Linearized_FDM
Non_linear_FDM
main %===========================PREAMBLE=====================================%
SOURCE CODE
function s = compute_w(Ra,Da,Nu,psi,xi,k_r)
    omega = xi + (1 - xi)*k_r;
    w1 = (Ra*Da)/(omega*psi^2);
    w2 = (Nu*(1-xi))/(omega*psi^2);
    s = [omega;w1;w2];
end