Description of main
main
PURPOSE
%===========================PREAMBLE=====================================%
SYNOPSIS
This is a script file.
DESCRIPTION
%===========================PREAMBLE=====================================%
author: R Surya Narayan (for all Analytical, FVM, NL-FDM and L-FDM solvers + performance)
performance plots generated by: Ritesh Kumar Singh
Date: 12th April 2021, Monday
Version: 2.0 (final, stable)
============================POROUS FIN SOLUTION==========================%
CROSS-REFERENCE INFORMATION
This function calls:
analytical_solution
Finite_Volume_Method
Linearized_FDM
Non_linear_FDM
compute_w
performance_eval
This function is called by:
SOURCE CODE
%%===========================PREAMBLE=====================================%
%author: R Surya Narayan (for all Analytical, FVM, NL-FDM and L-FDM solvers + performance)
%performance plots generated by: Ritesh Kumar Singh
%Date: 12th April 2021, Monday
%Version: 2.0 (final, stable)
%============================POROUS FIN SOLUTION==========================%
close all; clear all; clc;
%derive params w1 and w2
Ra = 1000;
Da = 0.04;
Nu = 10;
psi = 0.05;
xi = 0.8;
k_r = 7000;
omg = compute_w(Ra,Da,Nu,psi,xi,k_r);
omega = omg(1);
w1 = omg(2);
w2 = omg(3);
%set params
mesh=100;
params=[Ra;Da;Nu;psi;xi;k_r];
tol = 1e-10;
%%=============================NON-LINEAR FDM============================%%
[t_1,x] = Non_linear_FDM(params,mesh,tol);
[t,x] = analytical_solution(params,mesh);
err = 100*abs(t_1-t)./t;
figure(1)
plot(x,t_1,'+b');
hold on;
% plot(x,t,'-r');
% legend('NL-FDM','Actual');
% % post process data
perf = performance_eval(params,t_1);
Q = perf(1);
eta = perf(2);
epsilon = perf(3);
%==============================LINEARIZED FDM============================%%
[t,x] = Linearized_FDM(params,mesh,tol);
figure(1)
plot(x,t,'og');
%==================================FVM===================================%%
%construct x-vector
[t,x] = Finite_Volume_Method(params,mesh,tol);
%plot
figure(1)
plot(x,t,'-r');
legend('FDM-NL', 'FDM-L','FVM-L');
hold off;